services:
  server:
    image: ghcr.io/${GHCR_OWNER}/${GHCR_REPO}-server:${IMAGE_TAG}
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}-server.rule=Host(`${APP_DOMAIN}`)&& PathPrefix(`/api/v1`)"
      - "traefik.http.routers.${APP_NAME}-server.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}-server.tls.certresolver=letsencrypt"
      - "traefik.http.services.${APP_NAME}-server.loadbalancer.server.port=5000"
      # Ưu tiên API router
      - "traefik.http.routers.techreview-api.priority=100"
  client:
    image: ghcr.io/${GHCR_OWNER}/${GHCR_REPO}-client:${IMAGE_TAG}
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=letsencrypt"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=80"
      # Thấp hơn API router
      - "traefik.http.routers.techreview.priority=10"
networks:
  web:
    external: true